In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("C:/Users/Saee Beri/OneDrive/Desktop/Msc Datascience/Sem 2/heartdiseases.csv",na_values=-9)
data.shape

(282, 76)

In [3]:
#Load data and Set range -9 to NA 

data['V75']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
277     NaN
278     NaN
279    name
280     NaN
281     NaN
Name: V75, Length: 282, dtype: object

In [4]:
data_subset = data.iloc[:, :58]

In [5]:
data_subset.iloc[:, 57]= np.where(data_subset.iloc[:, 57] > 1, 1, data_subset.iloc[:, 57])

In [6]:
data_subset

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V49,V50,V51,V52,V53,V54,V55,V56,V57,V58
0,1,0,63,1,NaN,NaN,NaN,NaN,1,145,...,NaN,NaN,6.0,NaN,NaN,NaN,2,16,81,0
1,2,0,67,1,NaN,NaN,NaN,NaN,4,160,...,NaN,NaN,3.0,NaN,NaN,NaN,2,5,81,1
2,3,0,67,1,NaN,NaN,NaN,NaN,4,120,...,NaN,NaN,7.0,NaN,NaN,NaN,2,20,81,1
3,4,0,37,1,NaN,NaN,NaN,NaN,3,130,...,NaN,NaN,3.0,NaN,NaN,NaN,2,4,81,0
4,6,0,41,0,NaN,NaN,NaN,NaN,2,130,...,NaN,NaN,3.0,NaN,NaN,NaN,2,18,81,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277,294,0,39,0,NaN,NaN,NaN,NaN,3,138,...,NaN,NaN,3.0,NaN,NaN,NaN,5,9,84,0
278,295,0,57,1,NaN,NaN,NaN,NaN,2,154,...,NaN,NaN,3.0,NaN,NaN,NaN,6,5,84,1
279,296,0,58,0,NaN,NaN,NaN,NaN,4,130,...,NaN,NaN,3.0,NaN,NaN,NaN,3,29,84,0
280,297,0,57,1,NaN,NaN,NaN,NaN,4,110,...,NaN,NaN,7.0,NaN,NaN,NaN,5,4,84,1
281,298,0,47,1,NaN,NaN,NaN,NaN,3,130,...,NaN,NaN,3.0,NaN,NaN,NaN,5,24,84,0

In [7]:
numeric_data = data_subset.select_dtypes(include=[np.number])

In [8]:
cols_with_all_na = numeric_data.columns[numeric_data.isna().all()]
numeric_data.drop(columns=cols_with_all_na, inplace=True)

In [9]:
cols_with_na = numeric_data.columns[numeric_data.isna().any()]
for col in cols_with_na:
    mode_value = numeric_data[col].mode()[0]
    numeric_data[col].fillna(mode_value, inplace=True)

C:\Users\Saee Beri\AppData\Local\Temp\ipykernel_24008\223905000.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  numeric_data[col].fillna(mode_value, inplace=True)

In [10]:
numeric_data

,V1,V2,V3,V4,V7,V8,V9,V10,V11,V12,...,V42,V43,V44,V50,V51,V54,V55,V56,V57,V58
0,1,0,63,1,-18.0,3.0,1,145,1,233.0,...,105.0,172,0.0,7.0,6.0,2.0,2,16,81,0
1,2,0,67,1,-18.0,3.0,4,160,1,286.0,...,105.0,185,3.0,7.0,3.0,2.0,2,5,81,1
2,3,0,67,1,-18.0,3.0,4,120,1,229.0,...,105.0,150,2.0,7.0,7.0,2.0,2,20,81,1
3,4,0,37,1,-18.0,3.0,3,130,0,250.0,...,105.0,167,0.0,7.0,3.0,2.0,2,4,81,0
4,6,0,41,0,-18.0,3.0,2,130,1,204.0,...,105.0,40,0.0,7.0,3.0,2.0,2,18,81,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277,294,0,39,0,-18.0,3.0,3,138,1,220.0,...,105.0,161,0.0,7.0,3.0,2.0,5,9,84,0
278,295,0,57,1,-18.0,3.0,2,154,0,232.0,...,105.0,62,1.0,7.0,3.0,2.0,6,5,84,1
279,296,0,58,0,-18.0,3.0,4,130,1,197.0,...,105.0,94,0.0,7.0,3.0,2.0,3,29,84,0
280,297,0,57,1,-18.0,3.0,4,110,1,335.0,...,105.0,91,1.0,7.0,7.0,2.0,5,4,84,1
281,298,0,47,1,-18.0,3.0,3,130,1,253.0,...,105.0,55,0.0,7.0,3.0,2.0,5,24,84,0

In [11]:
print(numeric_data.describe())

               V1     V2          V3          V4     V7          V8  \
count  282.000000  282.0  282.000000  282.000000  282.0  282.000000
mean   151.517730    0.0   54.411348    0.677305  -18.0    3.003546
std     87.131234    0.0    9.053083    0.468338    0.0    0.059549
min      1.000000    0.0   29.000000    0.000000  -18.0    3.000000
25%     75.250000    0.0   48.000000    0.000000  -18.0    3.000000
50%    151.500000    0.0   55.000000    1.000000  -18.0    3.000000
75%    227.750000    0.0   61.000000    1.000000  -18.0    3.000000
max    298.000000    0.0   77.000000    1.000000  -18.0    4.000000

               V9         V10         V11         V12  ...         V42  \
count  282.000000  282.000000  282.000000  282.000000  ...  282.000000
mean     4.432624  130.269504    2.822695  249.046099  ...  105.819149
std     12.365608   22.218225   21.932859   51.011212  ...    8.026153
min      1.000000    1.000000    0.000000  126.000000  ...  105.000000
25%      3.000000  120.000000    0.000000  212.000000  ...  105.000000
50%      3.000000  130.000000    1.000000  244.000000  ...  105.000000
75%      4.000000  140.000000    1.000000  277.000000  ...  105.000000
max    130.000000  200.000000  253.000000  564.000000  ...  200.000000

              V43         V44         V50         V51         V54         V55  \
count  282.000000  282.000000  282.000000  282.000000  282.000000  282.000000
mean   121.290780    0.645390    6.985816    4.624113    2.063830    6.570922
std     48.558442    0.925208    0.238197    1.929501    0.717972    4.124867
min      0.000000    0.000000    3.000000    3.000000    2.000000    1.000000
25%     90.250000    0.000000    7.000000    3.000000    2.000000    3.000000
50%    117.500000    0.000000    7.000000    3.000000    2.000000    7.000000
75%    150.000000    1.000000    7.000000    7.000000    2.000000   10.000000
max    270.000000    3.000000    7.000000    7.000000   11.000000   29.000000

              V56         V57         V58
count  282.000000  282.000000  282.000000
mean    16.241135   81.152482    0.453901
std     11.754246    9.768211    0.498755
min      1.000000    0.000000    0.000000
25%      8.000000   82.000000    0.000000
50%     15.000000   82.000000    0.000000
75%     23.000000   83.000000    1.000000
max     82.000000   84.000000    1.000000

[8 rows x 49 columns]

In [12]:
numeric_data.to_csv("cleaned_data.csv", index=False)

In [13]:
cols_with_na = numeric_data.columns[numeric_data.isna().any()]
for col in cols_with_na:
    mode_value = numeric_data[col].mode()[0]
    numeric_data[col].fillna(mode_value, inplace=True)

In [2]:
pip install pandas

Collecting pandasNote: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

  Downloading pandas-2.2.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\saee beri\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\saee beri\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\saee beri\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.2.3-cp313-cp313-win_amd64.whl (11.5 MB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ----------- ---------------------------- 3.4/11.5 MB 21.6 MB/s eta 0:00:01
   ----------- ---------------------------- 3.4/11.5 MB 21.6 MB/s eta 0:00:01
   ------------------- -------------------- 5.5/11.5 MB 8.8 MB/s eta 0:00:01
   ----------------------- ---------------- 6.8/11.5 MB 8.4 MB/s eta 0:00:01
   ------------------------- -------------- 7.3/11.5 MB 7.6 MB/s eta 0:00:01
   ---------------------------- ----------- 8.1/11.5 MB 6.4 MB/s eta 0:00:01
   ------------------------------- -------- 9.2/11.5 MB 6.3 MB/s eta 0:00:01
   ------------------------------------ --- 10.5/11.5 MB 6.3 MB/s eta 0:00:01
   -------------------------------------- - 11.0/11.5 MB 5.8 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 5.5 MB/s eta 0:00:00
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.2.3 pytz-2025.2 tzdata-2025.2

In [14]:
cols_constant = numeric_data.columns[numeric_data.nunique() == 1]
numeric_data.drop(columns=cols_constant, inplace=True)

In [15]:
print(numeric_data.describe())

               V1          V3          V4          V8          V9         V10  \
count  282.000000  282.000000  282.000000  282.000000  282.000000  282.000000
mean   151.517730   54.411348    0.677305    3.003546    4.432624  130.269504
std     87.131234    9.053083    0.468338    0.059549   12.365608   22.218225
min      1.000000   29.000000    0.000000    3.000000    1.000000    1.000000
25%     75.250000   48.000000    0.000000    3.000000    3.000000  120.000000
50%    151.500000   55.000000    1.000000    3.000000    3.000000  130.000000
75%    227.750000   61.000000    1.000000    3.000000    4.000000  140.000000
max    298.000000   77.000000    1.000000    4.000000  130.000000  200.000000

              V11         V12         V13         V14  ...         V42  \
count  282.000000  282.000000  282.000000  282.000000  ...  282.000000
mean     2.822695  249.046099    0.177305   16.656028  ...  105.819149
std     21.932859   51.011212    2.143545   19.441090  ...    8.026153
min      0.000000  126.000000    0.000000    0.000000  ...  105.000000
25%      0.000000  212.000000    0.000000    0.000000  ...  105.000000
50%      1.000000  244.000000    0.000000   10.000000  ...  105.000000
75%      1.000000  277.000000    0.000000   30.000000  ...  105.000000
max    253.000000  564.000000   30.000000   99.000000  ...  200.000000

              V43         V44         V50         V51         V54         V55  \
count  282.000000  282.000000  282.000000  282.000000  282.000000  282.000000
mean   121.290780    0.645390    6.985816    4.624113    2.063830    6.570922
std     48.558442    0.925208    0.238197    1.929501    0.717972    4.124867
min      0.000000    0.000000    3.000000    3.000000    2.000000    1.000000
25%     90.250000    0.000000    7.000000    3.000000    2.000000    3.000000
50%    117.500000    0.000000    7.000000    3.000000    2.000000    7.000000
75%    150.000000    1.000000    7.000000    7.000000    2.000000   10.000000
max    270.000000    3.000000    7.000000    7.000000   11.000000   29.000000

              V56         V57         V58
count  282.000000  282.000000  282.000000
mean    16.241135   81.152482    0.453901
std     11.754246    9.768211    0.498755
min      1.000000    0.000000    0.000000
25%      8.000000   82.000000    0.000000
50%     15.000000   82.000000    0.000000
75%     23.000000   83.000000    1.000000
max     82.000000   84.000000    1.000000

[8 rows x 46 columns]

In [16]:
numeric_data.to_csv("cleaned_data.csv", index=False)